@Host = https://localhost:7048
@ExistingBookId = 1d665949-a89d-4a0a-aff9-6c8fee8be2b9
@CreatedBookId = 22da01ad-c2fc-4786-aac9-b3d0860a90a7

@CreatedUserEmail = jon@example.com
@CreatedUserPassword = P@ssword123!!
@CreatedUserStreetAddressId = 710f7f79-7186-4b04-8d14-cc9d93dcfb42

GET {{Host}}/books/
Accept: application/json

###

# GET existing Book
GET {{Host}}/books/{{ExistingBookId}}
Accept: application/json

###

# GET not-existing Book (404)
GET {{Host}}/books/00000000-0000-0000-0000-000000000000
Accept: application/json

###

# POST new Book
POST {{Host}}/books
Accept: application/json
Content-Type: application/json

{
  "id": "{{CreatedBookId}}",
  "title": "The Hobbit",
  "author": "J.R.R. Tolkien",
  "price": 50.99
}

###

# GET created Book (testing Location header)
GET {{Host}}/Books/{{CreatedBookId}}
Accept: application/json

###

# UPDATE Book Price

POST {{Host}}/Books/{{CreatedBookId}}/pricehistory
Accept: application/json
Content-Type: application/json

{
  "id": "{{ExistingBookId}}",
  "newPrice": 10000.50
}

###

# DELETE Book
DELETE {{Host}}/Books/{{CreatedBookId}}
Accept: application/json

###

# Create User
POST {{Host}}/users
Accept: application/json
Content-Type: application/json

{
  "email": "{{CreatedUserEmail}}",
  "password": "{{CreatedUserPassword}}"
}

###

# Login as User
POST {{Host}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "{{CreatedUserEmail}}",
  "password": "{{CreatedUserPassword}}"
}

###

# Replace with token retrieved in above Login request
@token = abc123

# Add item to cart
POST {{Host}}/cart
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "bookId": "{{ExistingBookId}}",
  "quantity": 1
}

###

# List Cart Items
GET {{Host}}/cart
Accept: application/json
Authorization: Bearer {{token}}

###

# List All Orders
GET {{Host}}/orders
Authorization: Bearer {{token}}
Accept: application/json

###

# Checkout (not using address IDs currently)
POST {{Host}}/cart/checkout
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "shippingAddressId": "{{CreatedUserStreetAddressId}}",
  "billingAddressId": "{{CreatedUserStreetAddressId}}"
}

###

# List Addresses
GET {{Host}}/users/addresses
Authorization: Bearer {{token}}
Accept: application/json

###

# Add Address
POST {{Host}}/users/addresses
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "street1": "123 Fake Street",
  "street2": "",
  "city": "Beverly Hills",
  "state": "California",
  "postalCode": "90210",
  "country": "USA"
}
